#!/bin/bash
# if nothing is passed to the script, show usage and exit
[[ -n "$1" ]] || { echo "Usage: findlarge PATHNAME [limit in MB]"; exit 0 ; }
LIMIT=${2:-25}
# simple using find, $1 is the first variable passed to the script
#find $1 -type f -size +${LIMIT}M -exec stat -f '%z %N' {} \; | sort -n -r | awk '{ $1=sprintf("%dM\t",($1/1024^2)); }1'
find $1 -type f -size +${LIMIT}M -print0 | xargs -0 stat -f '%z %N' | sort -n -r | awk '{ $1=sprintf("%dM\t",($1/1024^2)); }1'
